import { Game } from './types';

export const fortnitePreset: Omit<Game, 'id' | 'created_at'> = {
  name: 'Fortnite',
  slug: 'fortnite',
  category: 'Shooter / Cosmetics',
  description: 'Accounts with levels and cosmetics (skins, pickaxes, emotes, gliders).',
  api_base_url: 'https://prod-api.lzt.market',
  list_path: '/fortnite',
  check_path_template: '/{id}/check-account',
  default_filters: { currency: 'usd' },
  columns: [
    { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
    { id: 'title', label: 'Title', type: 'core', min_width: '20rem' },
    { id: 'url', label: 'URL', type: 'core' },
    { id: 'price', label: 'Price', type: 'core', is_numeric: true },
    { id: 'currency', label: 'Currency', type: 'core' },
    { id: 'deal_score', label: 'Deal Score', type: 'core', is_numeric: true },
    { id: 'fortnite_level', label: 'Level', type: 'game_specific', is_numeric: true },
    { id: 'fortnite_balance', label: 'V-Bucks', type: 'game_specific', is_numeric: true },
    { id: 'fortnite_skin_count', label: 'Skins', type: 'game_specific', is_numeric: true },
    { id: 'fortnite_pickaxe_count', label: 'Pickaxes', type: 'game_specific', is_numeric: true },
    { id: 'fortnite_dance_count', label: 'Emotes', type: 'game_specific', is_numeric: true },
    { id: 'fortnite_glider_count', label: 'Gliders', type: 'game_specific', is_numeric: true },
    { id: 'first_seen_at', label: 'First Seen', type: 'core' },
    { id: 'last_seen_at', label: 'Last Seen', type: 'core' },
  ],
  filters: [
    { id: 'title', label: 'Search', type: 'text', is_advanced: false, param_name: 'title' },
    { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
    { id: 'fortnite_level', label: 'Level', type: 'number_range', is_advanced: false, param_name_min: 'lmin', param_name_max: 'lmax' },
    { id: 'fortnite_balance', label: 'V-Bucks', type: 'number_range', is_advanced: false, param_name_min: 'vbmin', param_name_max: 'vbmax' },
    { id: 'fortnite_skin_count', label: 'Skins Count', type: 'number_range', is_advanced: true, param_name_min: 'smin', param_name_max: 'smax' },
    { id: 'fortnite_pickaxe_count', label: 'Pickaxes Count', type: 'number_range', is_advanced: true, param_name_min: 'pickaxes_shop_min', param_name_max: 'pickaxes_shop_max' },
    { id: 'fortnite_dance_count', label: 'Emotes Count', type: 'number_range', is_advanced: true, param_name_min: 'dances_shop_min', param_name_max: 'dances_shop_max' },
    { id: 'fortnite_glider_count', label: 'Gliders Count', type: 'number_range', is_advanced: true, param_name_min: 'gliders_shop_min', param_name_max: 'gliders_shop_max' },
  ],
  sorts: [
    { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
    { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
    { id: 'price_desc', label: 'Price: High to Low', column: 'price', ascending: false },
    { id: 'deal_score', label: 'Deal Score', column: 'deal_score', ascending: false },
  ],
};

export const wotPreset: Omit<Game, 'id' | 'created_at'> = {
  name: 'World of Tanks',
  slug: 'world-of-tanks',
  category: 'Vehicles / MMO',
  description: 'Accounts characterized by tanks, premium status, resources, battles, wins.',
  api_base_url: 'https://prod-api.lzt.market',
  list_path: '/world-of-tanks',
  check_path_template: '/{id}/check-account',
  default_filters: { currency: 'usd' },
  columns: [
    { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
    { id: 'title', label: 'Title', type: 'core', min_width: '20rem' },
    { id: 'url', label: 'URL', type: 'core' },
    { id: 'price', label: 'Price', type: 'core', is_numeric: true },
    { id: 'currency', label: 'Currency', type: 'core' },
    { id: 'deal_score', label: 'Deal Score', type: 'core', is_numeric: true },
    { id: 'wot_gold', label: 'Gold', type: 'game_specific', is_numeric: true },
    { id: 'wot_credits', label: 'Credits', type: 'game_specific', is_numeric: true },
    { id: 'wot_battle_count', label: 'Battles', type: 'game_specific', is_numeric: true },
    { id: 'wot_win_count', label: 'Wins', type: 'game_specific', is_numeric: true },
    { id: 'wot_win_count_percents', label: 'Win %', type: 'game_specific', is_numeric: true },
    { id: 'wot_top_tanks', label: 'Top Tanks', type: 'game_specific', is_numeric: true },
    { id: 'wot_premium_tanks', label: 'Premium Tanks', type: 'game_specific', is_numeric: true },
    { id: 'wot_last_activity', label: 'Last Activity', type: 'game_specific' },
    { id: 'first_seen_at', label: 'First Seen', type: 'core' },
    { id: 'last_seen_at', label: 'Last Seen', type: 'core' },
  ],
  filters: [
    { id: 'title', label: 'Search', type: 'text', is_advanced: false, param_name: 'title' },
    { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
    { id: 'wargaming_battles', label: 'Battles', type: 'number_range', is_advanced: false, param_name_min: 'wargaming_battles_min', param_name_max: 'wargaming_battles_max' },
    { id: 'wargaming_win_pmin', label: 'Win %', type: 'number_range', is_advanced: false, param_name_min: 'wargaming_win_pmin', param_name_max: 'wargaming_win_pmax' },
    { id: 'wargaming_gold', label: 'Gold', type: 'number_range', is_advanced: true, param_name_min: 'wargaming_gold_min', param_name_max: 'wargaming_gold_max' },
  ],
  sorts: [
    { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
    { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
    { id: 'gold_desc', label: 'Gold: High to Low', column: 'wot_gold', ascending: false },
    { id: 'deal_score', label: 'Deal Score', column: 'deal_score', ascending: false },
  ],
};

export const mihoyoPreset: Omit<Game, 'id' | 'created_at'> = {
    name: 'miHoYo',
    slug: 'mihoyo',
    category: 'RPG / Characters',
    description: 'Accounts defined by region, progression, character and legendary sets.',
    api_base_url: 'https://prod-api.lzt.market',
    list_path: '/mihoyo',
    check_path_template: '/{id}/check-account',
    default_filters: { currency: 'usd' },
    columns: [
      { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
      { id: 'url', label: 'URL', type: 'core' },
      { id: 'price', label: 'Price', type: 'core', is_numeric: true },
      { id: 'currency', label: 'Currency', type: 'core' },
      { id: 'deal_score', label: 'Deal Score', type: 'core', is_numeric: true },
      { id: 'mihoyo_region', label: 'Region', type: 'game_specific' },
      { id: 'mihoyo_genshin_level', label: 'Genshin Level', type: 'game_specific', is_numeric: true },
      { id: 'mihoyo_genshin_character_count', label: 'Genshin Chars', type: 'game_specific', is_numeric: true },
      { id: 'mihoyo_genshin_legendary_characters_count', label: 'Genshin 5*', type: 'game_specific', is_numeric: true },
      { id: 'mihoyo_honkai_level', label: 'Honkai Level', type: 'game_specific', is_numeric: true },
      { id: 'first_seen_at', label: 'First Seen', type: 'core' },
      { id: 'last_seen_at', label: 'Last Seen', type: 'core' },
    ],
    filters: [
        { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
        { id: 'region', label: 'Region', type: 'select', is_advanced: false, param_name: 'region[]', options: ['asia', 'cht', 'eu', 'usa'] },
        { id: 'genshin_level', label: 'Genshin Level', type: 'number_range', is_advanced: true, param_name_min: 'genshin_level_min', param_name_max: 'genshin_level_max'},
        { id: 'genshin_char', label: 'Genshin Chars', type: 'number_range', is_advanced: true, param_name_min: 'genshin_char_min', param_name_max: 'genshin_char_max'},
        { id: 'genshin_legendary', label: 'Genshin 5*', type: 'number_range', is_advanced: true, param_name_min: 'genshin_legendary_min', param_name_max: 'genshin_legendary_max'},
    ],
    sorts: [
        { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
        { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
        { id: 'price_desc', label: 'Price: High to Low', column: 'price', ascending: false },
        { id: 'power_desc', label: '"Power": High to Low', column: 'mihoyo_genshin_legendary_characters_count', ascending: false },
        { id: 'deal_score', label: 'Deal Score', column: 'deal_score', ascending: false },
    ],
};

export const steamPreset: Omit<Game, 'id' | 'created_at'> = {
  name: 'Steam',
  slug: 'steam',
  category: 'PC Gaming Platform',
  description: 'General Steam accounts with various games, levels, and items.',
  api_base_url: 'https://prod-api.lzt.market',
  list_path: '/steam',
  check_path_template: '/{id}/check-account',
  default_filters: { currency: 'usd' },
  columns: [
    { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
    { id: 'title', label: 'Title', type: 'core', min_width: '20rem' },
    { id: 'url', label: 'URL', type: 'core' },
    { id: 'price', label: 'Price', type: 'core', is_numeric: true },
    { id: 'deal_score', label: 'Deal Score', type: 'core', is_numeric: true },
    { id: 'steam_level', label: 'Level', type: 'game_specific', is_numeric: true },
    { id: 'steam_game_count', label: 'Games', type: 'game_specific', is_numeric: true },
    { id: 'steam_balance', label: 'Balance', type: 'game_specific' },
    { id: 'steam_cs2_rank_id', label: 'CS2 Rank', type: 'game_specific' },
    { id: 'steam_cs2_win_count', label: 'CS2 Wins', type: 'game_specific', is_numeric: true },
    { id: 'steam_dota2_solo_mmr', label: 'Dota2 MMR', type: 'game_specific', is_numeric: true },
  ],
  filters: [
    { id: 'title', label: 'Search', type: 'text', is_advanced: false, param_name: 'title' },
    { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
    { id: 'steam_level', label: 'Level', type: 'number_range', is_advanced: false, param_name_min: 'lmin', param_name_max: 'lmax' },
    { id: 'steam_game_count', label: 'Games', type: 'number_range', is_advanced: true, param_name_min: 'gmin', param_name_max: 'gmax' },
    { id: 'steam_balance', label: 'Balance', type: 'number_range', is_advanced: true, param_name_min: 'balance_min', param_name_max: 'balance_max' },
  ],
  sorts: [
    { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
    { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
    { id: 'price_desc', label: 'Price: High to Low', column: 'price', ascending: false },
  ],
};

export const riotPreset: Omit<Game, 'id' | 'created_at'> = {
  name: 'Riot Games',
  slug: 'riot',
  category: 'MOBA / Shooter',
  description: 'Valorant and League of Legends accounts.',
  api_base_url: 'https://prod-api.lzt.market',
  list_path: '/riot',
  check_path_template: '/{id}/check-account',
  default_filters: { currency: 'usd' },
  columns: [
    { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
    { id: 'title', label: 'Title', type: 'core', min_width: '20rem' },
    { id: 'url', label: 'URL', type: 'core' },
    { id: 'price', label: 'Price', type: 'core', is_numeric: true },
    { id: 'deal_score', label: 'Deal Score', type: 'core', is_numeric: true },
    { id: 'riot_valorant_level', label: 'Valorant Lvl', type: 'game_specific', is_numeric: true },
    { id: 'riot_valorant_rank', label: 'Valorant Rank', type: 'game_specific' },
    { id: 'riot_valorant_skin_count', label: 'Valorant Skins', type: 'game_specific', is_numeric: true },
    { id: 'riot_lol_level', label: 'LoL Lvl', type: 'game_specific', is_numeric: true },
    { id: 'riot_lol_skin_count', label: 'LoL Skins', type: 'game_specific', is_numeric: true },
    { id: 'riot_lol_rank', label: 'LoL Rank', type: 'game_specific' },
  ],
  filters: [
    { id: 'title', label: 'Search', type: 'text', is_advanced: false, param_name: 'title' },
    { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
    { id: 'riot_valorant_level', label: 'Valorant Level', type: 'number_range', is_advanced: true, param_name_min: 'valorant_level_min', param_name_max: 'valorant_level_max' },
    { id: 'riot_lol_level', label: 'LoL Level', type: 'number_range', is_advanced: true, param_name_min: 'lol_level_min', param_name_max: 'lol_level_max' },
  ],
  sorts: [
    { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
    { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
  ],
};

export const socialClubPreset: Omit<Game, 'id' | 'created_at'> = {
  name: 'Social Club',
  slug: 'socialclub',
  category: 'Action-Adventure',
  description: 'Rockstar Games Social Club accounts, primarily for GTA V.',
  api_base_url: 'https://prod-api.lzt.market',
  list_path: '/socialclub',
  check_path_template: '/{id}/check-account',
  default_filters: { currency: 'usd' },
  columns: [
    { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
    { id: 'title', label: 'Title', type: 'core', min_width: '20rem' },
    { id: 'url', label: 'URL', type: 'core' },
    { id: 'price', label: 'Price', type: 'core', is_numeric: true },
    { id: 'deal_score', label: 'Deal Score', type: 'core', is_numeric: true },
    { id: 'socialclub_level', label: 'Level', type: 'game_specific', is_numeric: true },
    { id: 'socialclub_cash', label: 'Cash', type: 'game_specific', is_numeric: true },
    { id: 'socialclub_bank_cash', label: 'Bank', type: 'game_specific', is_numeric: true },
    { id: 'socialclub_has_gtav', label: 'Has GTA V', type: 'game_specific' },
    { id: 'socialclub_has_rdr2', label: 'Has RDR2', type: 'game_specific' },
  ],
  filters: [
    { id: 'title', label: 'Search', type: 'text', is_advanced: false, param_name: 'title' },
    { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
    { id: 'socialclub_level', label: 'Level', type: 'number_range', is_advanced: true, param_name_min: 'level_min', param_name_max: 'level_max' },
    { id: 'socialclub_cash', label: 'Cash', type: 'number_range', is_advanced: true, param_name_min: 'cash_min', param_name_max: 'cash_max' },
  ],
  sorts: [
    { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
    { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
  ],
};

export const escapeFromTarkovPreset: Omit<Game, 'id' | 'created_at'> = {
    name: 'Escape from Tarkov',
    slug: 'escape-from-tarkov',
    category: 'Hardcore Shooter',
    description: 'EFT accounts with different game versions and progression.',
    api_base_url: 'https://prod-api.lzt.market',
    list_path: '/escape-from-tarkov',
    check_path_template: '/{id}/check-account',
    default_filters: { currency: 'usd' },
    columns: [
        { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
        { id: 'title', label: 'Title', type: 'core', min_width: '20rem' },
        { id: 'url', label: 'URL', type: 'core' },
        { id: 'price', label: 'Price', type: 'core', is_numeric: true },
        { id: 'deal_score', label: 'Deal Score', type: 'core', is_numeric: true },
        { id: 'tarkov_game_version', label: 'Version', type: 'game_specific' },
        { id: 'tarkov_level', label: 'Level', type: 'game_specific', is_numeric: true },
        { id: 'tarkov_rubles', label: 'Rubles', type: 'game_specific', is_numeric: true },
        { id: 'tarkov_kd', label: 'K/D', type: 'game_specific', is_numeric: true },
    ],
    filters: [
        { id: 'title', label: 'Search', type: 'text', is_advanced: false, param_name: 'title' },
        { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
        { id: 'tarkov_level', label: 'Level', type: 'number_range', is_advanced: true, param_name_min: 'level_min', param_name_max: 'level_max' },
        { id: 'tarkov_game_version', label: 'Version', type: 'select', is_advanced: false, param_name: 'version[]', options: ['standard', 'left_behind', 'prepare_for_escape', 'edge_of_darkness', 'unheard_edition'] },
    ],
    sorts: [
        { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
        { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
    ],
};

export const minecraftPreset: Omit<Game, 'id' | 'created_at'> = {
    name: 'Minecraft',
    slug: 'minecraft',
    category: 'Sandbox',
    description: 'Minecraft accounts with capes and Hypixel stats.',
    api_base_url: 'https://prod-api.lzt.market',
    list_path: '/minecraft',
    check_path_template: '/{id}/check-account',
    default_filters: { currency: 'usd' },
    columns: [
        { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
        { id: 'title', label: 'Title', type: 'core', min_width: '20rem' },
        { id: 'url', label: 'URL', type: 'core' },
        { id: 'price', label: 'Price', type: 'core', is_numeric: true },
        { id: 'minecraft_nickname', label: 'Nickname', type: 'game_specific' },
        { id: 'minecraft_can_change_nickname', label: 'Change Nick', type: 'game_specific' },
        { id: 'minecraft_hypixel_rank', label: 'Hypixel Rank', type: 'game_specific' },
        { id: 'minecraft_hypixel_level', label: 'Hypixel Level', type: 'game_specific', is_numeric: true },
        { id: 'minecraft_capes_count', label: 'Capes', type: 'game_specific', is_numeric: true },
    ],
    filters: [
        { id: 'title', label: 'Search', type: 'text', is_advanced: false, param_name: 'title' },
        { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
        { id: 'minecraft_hypixel_level', label: 'Hypixel Level', type: 'number_range', is_advanced: true, param_name_min: 'level_hypixel_min', param_name_max: 'level_hypixel_max' },
    ],
    sorts: [
        { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
        { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
    ],
};

export const robloxPreset: Omit<Game, 'id' | 'created_at'> = {
    name: 'Roblox',
    slug: 'roblox',
    category: 'Online Game Platform',
    description: 'Roblox accounts with Robux, friends, and followers.',
    api_base_url: 'https://prod-api.lzt.market',
    list_path: '/roblox',
    check_path_template: '/{id}/check-account',
    default_filters: { currency: 'usd' },
    columns: [
        { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
        { id: 'title', label: 'Title', type: 'core', min_width: '20rem' },
        { id: 'url', label: 'URL', type: 'core' },
        { id: 'price', label: 'Price', type: 'core', is_numeric: true },
        { id: 'roblox_robux', label: 'Robux', type: 'game_specific', is_numeric: true },
        { id: 'roblox_friends', label: 'Friends', type: 'game_specific', is_numeric: true },
        { id: 'roblox_followers', label: 'Followers', type: 'game_specific', is_numeric: true },
        { id: 'roblox_subscription', label: 'Subscription', type: 'game_specific' },
    ],
    filters: [
        { id: 'title', label: 'Search', type: 'text', is_advanced: false, param_name: 'title' },
        { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
        { id: 'roblox_robux', label: 'Robux', type: 'number_range', is_advanced: false, param_name_min: 'robux_min', param_name_max: 'robux_max' },
    ],
    sorts: [
        { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
        { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
    ],
};

export const epicGamesPreset: Omit<Game, 'id' | 'created_at'> = {
    name: 'Epic Games',
    slug: 'epicgames',
    category: 'Digital Storefront',
    description: 'Epic Games accounts with various games and balances.',
    api_base_url: 'https://prod-api.lzt.market',
    list_path: '/epicgames',
    check_path_template: '/{id}/check-account',
    default_filters: { currency: 'usd' },
    columns: [
        { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
        { id: 'title', label: 'Title', type: 'core', min_width: '20rem' },
        { id: 'url', label: 'URL', type: 'core' },
        { id: 'price', label: 'Price', type: 'core', is_numeric: true },
        { id: 'eg_game_count', label: 'Games', type: 'game_specific', is_numeric: true },
        { id: 'eg_balance', label: 'Balance', type: 'game_specific', is_numeric: true },
    ],
    filters: [
        { id: 'title', label: 'Search', type: 'text', is_advanced: false, param_name: 'title' },
        { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
        { id: 'eg_game_count', label: 'Games Count', type: 'number_range', is_advanced: true, param_name_min: 'gmin', param_name_max: 'gmax' },
    ],
    sorts: [
        { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
        { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
    ],
};

export const uplayPreset: Omit<Game, 'id' | 'created_at'> = {
    name: 'Uplay (Ubisoft)',
    slug: 'uplay',
    category: 'Digital Storefront',
    description: 'Ubisoft accounts, often with Rainbow Six Siege stats.',
    api_base_url: 'https://prod-api.lzt.market',
    list_path: '/uplay',
    check_path_template: '/{id}/check-account',
    default_filters: { currency: 'usd' },
    columns: [
        { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
        { id: 'title', label: 'Title', type: 'core', min_width: '20rem' },
        { id: 'url', label: 'URL', type: 'core' },
        { id: 'price', label: 'Price', type: 'core', is_numeric: true },
        { id: 'uplay_game_count', label: 'Games', type: 'game_specific', is_numeric: true },
        { id: 'uplay_r6_level', label: 'R6 Level', type: 'game_specific', is_numeric: true },
        { id: 'uplay_r6_rank', label: 'R6 Rank', type: 'game_specific' },
    ],
    filters: [
        { id: 'title', label: 'Search', type: 'text', is_advanced: false, param_name: 'title' },
        { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
        { id: 'uplay_game_count', label: 'Games Count', type: 'number_range', is_advanced: true, param_name_min: 'gmin', param_name_max: 'gmax' },
    ],
    sorts: [
        { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
        { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
    ],
};

export const battlenetPreset: Omit<Game, 'id' | 'created_at'> = {
    name: 'Battle.net',
    slug: 'battlenet',
    category: 'Digital Storefront',
    description: 'Blizzard Battle.net accounts.',
    api_base_url: 'https://prod-api.lzt.market',
    list_path: '/battlenet',
    check_path_template: '/{id}/check-account',
    default_filters: { currency: 'usd' },
    columns: [
        { id: 'item_id', label: 'Item ID', type: 'core', is_numeric: true },
        { id: 'title', label: 'Title', type: 'core', min_width: '20rem' },
        { id: 'url', label: 'URL', type: 'core' },
        { id: 'price', label: 'Price', type: 'core', is_numeric: true },
        { id: 'battlenet_balance', label: 'Balance', type: 'game_specific' },
        { id: 'battlenet_country', label: 'Country', type: 'game_specific' },
        { id: 'battlenet_can_change_tag', label: 'Can change tag', type: 'game_specific' },
    ],
    filters: [
        { id: 'title', label: 'Search', type: 'text', is_advanced: false, param_name: 'title' },
        { id: 'price', label: 'Price', type: 'number_range', is_advanced: false, param_name_min: 'pmin', param_name_max: 'pmax' },
        { id: 'battlenet_balance', label: 'Balance', type: 'number_range', is_advanced: true, param_name_min: 'balance_min', param_name_max: 'balance_max' },
    ],
    sorts: [
        { id: 'newest', label: 'Newest First', column: 'last_seen_at', ascending: false },
        { id: 'price_asc', label: 'Price: Low to High', column: 'price', ascending: true },
    ],
};

export const gamePresets = {
    fortnite: fortnitePreset,
    'world-of-tanks': wotPreset,
    mihoyo: mihoyoPreset,
    steam: steamPreset,
    riot: riotPreset,
    socialclub: socialClubPreset,
    'escape-from-tarkov': escapeFromTarkovPreset,
    minecraft: minecraftPreset,
    roblox: robloxPreset,
    epicgames: epicGamesPreset,
    uplay: uplayPreset,
    battlenet: battlenetPreset,
}
